version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: yarn dev
    ports:
      - "3000:3000" # host:container
    environment:
      PORT: 3000
      DATABASE_URL: postgres://photon_user:photon_password@postgres:5432/photon_decode
      NODE_ENV: development
    volumes:
      - ./backend:/usr/src/app/backend
      - ./uploads:/usr/src/app/uploads
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: photon_decode
      POSTGRES_USER: photon_user
      POSTGRES_PASSWORD: photon_password
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/db/init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - "5432:5432"

volumes:
  pgdata:
